import java.io.PrintWriter;
public class PayrollSystem {
    public static void main(String[] args) {
        Employee[] employees = {
            new FullTimeEmployee("Ali","FT101", 60000),
            new PartTimeEmployee("Nargiza","PT202", 20, 80),
            new CommissionEmployee("Yuliya","CM303", 2000, 10000, 0.1),
            new FullTimeEmployee("Invalid", "FT404",-5000),
            new PartTimeEmployee("Test","PT505",-15, 40)
        };
        double totalPayroll = 0;
        for (Employee e :employees) {
            totalPayroll += e.printPaySlip();
        }
        System.out.printf("Total valid monthly payroll: ", totalPayroll);
        try (PrintWriter writer = new PrintWriter("payroll_report.txt")) {
            writer.println("Payroll Summary");
            writer.println("===============");
            writer.printf("Total valid monthly payroll:", totalPayroll);
            writer.println("Generated by PayrollSystem");
        } catch (Exception e) {
            System.out.println("Error writing report:" + e.getMessage());
        }
    }
}
